require('plugins')
require('settings')
require('keymappings')
require('formatting')
require('colorscheme')
vim.cmd('source $HOME/.config/nvim/vimscript/lv-coc.vim')

require('lv-colorizer')
require('lv-fterm')
require('lv-galaxyline')
require('lv-nvimtree')
require('lv-pairs')
require('lv-surround')
require('lv-treesitter')
